import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { I18nProvider } from "@/components/providers/I18NProvider";
import Script from "next/script";
import FloatingNavbar from "@/components/ui/Nav/NavBar";
import Footer from "@/components/ui/Footer/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"
          strategy="lazyOnload"
        />
      </head>
      <body>
        <I18nProvider defaultLanguage="en">
          <FloatingNavbar />
          {children}
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
